### ISSUE TITLE
Download citations only

### ISSUE THREAD

**Issue by dimkadimon** [wikicite/wikicite-data#15]
I wanted to use this code to download the citations from wikidata. However I had to download the whole wikidata file (latest-all.json.bz2). This file was 32Gb and when I tried to extract it I ran out of space on my machine as it was 120+Gb! It would be really nice if someone could provide just the extracted citations from this data (result of running make 20170626/wikidata-20170626.pubtypes). I would really appreciate your help!

**Comment by nichtich** [comment]
See http://uri.gbv.de/wikicite/20181217/ for my current copy. The CSV file with citation links is 3.2Gb uncompressed.

**Comment by dimkadimon** [comment]
Thank you so much. Just what I needed!
